database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  name: bjj_store
  ssl_mode: disable

server:
  port: 8080
  environment: development

jwt:
  secret: bjj-store-jwt-secret-change-in-production-2024

admin:
  default_email: admin@bjjstore.com
  default_password: admin123

minio:
  endpoint: localhost:9000
  access_key_id: admin
  secret_access_key: admin123456
  bucket_name: bjj-store-images
  use_ssl: false
  region: us-east-1
